name: Continuous Integration

on:
  pull_request:
    branches: main
    paths:
      - '.github/workflows/continuous-integration.yaml'
      - 'action.yaml'
  workflow_dispatch:

jobs:
  validate-action:
    name: Validate action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_case:
          # zero version start
          - { bump_type: "major", initial_tag: "v0.0.0", expected_version: "v1.0.0" }
          - { bump_type: "minor", initial_tag: "v0.0.0", expected_version: "v0.1.0" }
          - { bump_type: "patch", initial_tag: "v0.0.0", expected_version: "v0.0.1" }

          # no tags present (simulating fresh repo without tags)
          - { bump_type: "major", initial_tag: "", expected_version: "v1.0.0" }
          - { bump_type: "minor", initial_tag: "", expected_version: "v0.1.0" }
          - { bump_type: "patch", initial_tag: "", expected_version: "v0.0.1" }

          # boundary bump from v9.9.9
          - { bump_type: "major", initial_tag: "v9.9.9", expected_version: "v10.0.0" }
          - { bump_type: "minor", initial_tag: "v9.9.9", expected_version: "v9.10.0" }
          - { bump_type: "patch", initial_tag: "v9.9.9", expected_version: "v9.9.10" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tagstronaut Action in debug mode
        id: version_bump
        uses: ./
        with:
          bump_type: ${{ matrix.test_case.bump_type }}
          debug: true
          debug_init_tag: ${{ matrix.test_case.initial_tag }}
      
      - name: Verify Output
        run: |
          expected_version="${{ matrix.test_case.expected_version }}"
          actual_version="${{ steps.version_bump.outputs.new_version }}"
          
          if [[ "$actual_version" != "$expected_version" ]]; then
            echo "❌ Test failed: Expected $expected_version but got $actual_version"
            exit 1
          else
            echo "✅ Test passed: Version is $actual_version as expected."
          fi
